derb/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',
        include('report_builder.urls', namespace='report_builder')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^password_recovery/', include('password_reset.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# DEPENDENCIES URLS
urlpatterns += [
    #url(r'^ckeditor/', include('ckeditor.urls'))
]

report_builder/urls.py
from django.conf.urls import include
from django.conf.urls import url

from report_builder import initial_views as init
from report_builder import views
from report_builder.Question import QuestionView
from report_builder.Question.QuestionType import (table_question,
                                                  simple_text_question,
                                                  multiple_selection_question,
                                                  boolean_question,
                                                  integer_question,
                                                  float_question,
                                                  unique_selection_question,
                                                  model_info,
                                                  question_model_info)
from report_builder.Question.QuestionType.simple_text_question import submit_new_observation
from report_builder.Question.QuestionType.unique_selection_question import get_catalog_display_fields
from report_builder.Question.question_loader import process_question
from report_builder.views import Report

# Boolean question
# Integer question
# Float question
# Simple text question
# Unique selection question
# Multiple selection question
# Model info
# Model info with questions
question_types_urls = [
    url(r'base/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', QuestionView.QuestionViewAdmin.as_view(),
        name='base_question_admin'),
    url(r'base/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', QuestionView.QuestionViewResp.as_view(),
        name='base_question_resp'),
    url(r'boolean/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', boolean_question.BooleanQuestionViewAdmin.as_view(),
        name='boolean_question_admin'),
    url(r'boolean/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewResp.as_view(),
        name='boolean_question_resp'),
    url(r'boolean/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewPDF.as_view(),
        name='boolean_question_pdf'),
    url(r'boolean/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        boolean_question.BooleanQuestionViewReviewer.as_view(),
        name='boolean_question_revisor'),
    url(r'boolean/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewCSV.as_view(),
        name='boolean_question_csv'),
    url(r'boolean/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewJSON.as_view(),
        name='boolean_question_json'),
    url(r'boolean/spss/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewSPSS.as_view(),
        name='boolean_question_spss'),
    url(r'integer/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', integer_question.IntegerQuestionViewAdmin.as_view(),
        name='integer_question_admin'),
    url(r'integer/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', integer_question.IntegerQuestionViewResp.as_view(),
        name='integer_question_resp'),
    url(r'integer/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', integer_question.IntegerQuestionViewPDF.as_view(),
        name='integer_question_pdf'),
    url(r'integer/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        integer_question.IntegerQuestionViewReviewer.as_view(),
        name='integer_question_revisor'),
    url(r'integer/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        integer_question.IntegerQuestionViewCSV.as_view(),
        name='integer_question_csv'),
    url(r'integer/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        integer_question.IntegerQuestionViewJSON.as_view(),
        name='integer_question_json'),
    url(r'float/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', float_question.FloatQuestionViewAdmin.as_view(),
        name='float_question_admin'),
    url(r'float/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', float_question.FloatQuestionViewResp.as_view(),
        name='float_question_resp'),
    url(r'float/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', float_question.FloatQuestionViewPDF.as_view(),
        name='float_question_pdf'),
    url(r'simple/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$',
        simple_text_question.SimpleTextQuestionViewAdmin.as_view(),
        name='simple_text_question_admin'),
    url(r'simple/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewResp.as_view(),
        name='simple_text_question_resp'),
    url(r'simple/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', simple_text_question.SimpleTextQuestionViewPDF.as_view(),
        name='simple_text_question_pdf'),
    url(r'simple/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        simple_text_question.SimpleTextQuestionViewReviewer.as_view(),
        name='simple_text_question_revisor'),
    url(r'simple/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewCSV.as_view(),
        name='simple_text_question_csv'),
    url(r'simple/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewJSON.as_view(),
        name='simple_text_question_json'),
    url(r"unique/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        unique_selection_question.UniqueSelectionQuestionViewAdmin.as_view(),
        name="unique_selection_admin"),
    url(r"unique/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        unique_selection_question.UniqueSelectionQuestionViewResp.as_view(),
        name="unique_selection_resp"),
    url(r"unique/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)",
        unique_selection_question.UniqueSelectionQuestionViewPDF.as_view(),
        name="unique_selection_pdf"),
    url(r'unique/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        unique_selection_question.UniqueSelectionQuestionViewReviewer.as_view(),
        name='unique_selection_question_revisor'),
    url(r'unique/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        unique_selection_question.UniqueQuestionViewCSV.as_view(),
        name='unique_selection_csv'),
    url(r'unique/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        unique_selection_question.UniqueQuestionViewJSON.as_view(),
        name='unique_selection_json'),
    url(r"table/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        table_question.TableQuestionViewAdmin.as_view(),
        name="table_question_admin"),
    url(r"table/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        table_question.TableQuestionViewResp.as_view(),
        name="table_question_resp"),
    url(r"table/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)",
        table_question.TableQuestionViewPDF.as_view(),
        name="table_question_pdf"),
    url(r'table/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        table_question.TableQuestionViewCSV.as_view(),
        name='table_question_csv'),
    url(r'table/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        table_question.TableQuestionViewJSON.as_view(),
        name='table_question_json'),
    url(r"multiple/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        multiple_selection_question.MultipleSelectionQuestionViewAdmin.as_view(),
        name="multiple_selection_admin"),
    url(r"multiple/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        multiple_selection_question.MultipleSelectionQuestionViewResp.as_view(),
        name="multiple_selection_resp"),
    url(r'multiple/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewPDF.as_view(),
        name='multiple_seletion_question_pdf'),
    url(r'multiple/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewCSV.as_view(),
        name='multiple_selection_question_csv'),
    url(r'multiple/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewJSON.as_view(),
        name='multiple_selection_question_json'),
    url(r'model_info/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?', model_info.ModelInfoViewAdmin.as_view(),
        name='model_info_question'),
    url(r'question_model_info/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?',
        question_model_info.QuestionModelInfoViewAdmin.as_view(), name='question_model_info_question')
]

# Report views
report_views_urls = [
    url(r'^new/$', init.NewReportView.as_view(), name='new_report'),
    url(r'^new/(?P<pk>\d+)$', init.NewReportTemplate,
        name='new_report_from_template'),
    url(r'^admin/template/(?P<pk>\d+)$', Report.admin, name='admin_report'),
    url(r'^admin/template/(?P<pk>\d+)/save$',
        Report.save_admin, name='admin_save_report'),
]

# Question processing
question_process_urls = [
    url(r'(?P<type>admin)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', process_question,
        name='process_admin'),
    url(r'(?P<type>responsable)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)/(?P<answer_pk>\d+)?$',
        process_question, name='process_responsable'),
    url(r'(?P<type>revisor)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)/(?P<answer_pk>\d+)?$',
        process_question, name='process_revisor')
]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^js/ckeditor_config.js', views.get_js_editor,
        name='js_ckeditor_config'),
    url(r'^init$', init.InitialIndexView.as_view(), name='init'),
    url(r'^question_types/', include(question_types_urls)),
    url(r'^report/', include(report_views_urls)),
    url(r'^question_processing/', include(question_process_urls)),
    url(r"^get_catalog_display_fields", get_catalog_display_fields,
        name='get_catalog_display_fields'),
    url(r"^submit_new_observation$", submit_new_observation,
        name='submit_new_observation')
]

report_builder/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from report_builder.models import Question, Answer, Report
from report_builder.report_shortcuts import get_question_permission


class QuestionForm(forms.ModelForm):
    children = forms.CharField

    class Meta:
        model = Question
        fields = ('text', 'help', 'required', 'id')
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 6,
                'placeholder': 'Write your question here',
                'class': 'form-control'
            }),
            'help': forms.Textarea(attrs={
                'cols': 80,
                'rows': 5,
                'placeholder': 'A little help never hurts',
                'class': 'form-control'
            })
        }
        exclude = ('order',)


class AnswerForm(forms.ModelForm):
    """
        TODO: docstring
    """

    def clean_text(self):
        text = self.cleaned_data['text']
        required = get_question_permission(self.instance.question)
        if required == 1 and not text:
            raise ValidationError(_('This field is required'), code='required')
        return text

    class Meta:
        model = Answer
        fields = ('annotation', 'text')
        widgets = {
            'annotation': forms.Textarea(attrs={
                'rows': 9,
                'placeholder': 'Annotations',
                'class': 'form-control'
            }),
            'text': forms.Textarea(attrs={
                'rows': 6,
                'placeholder': 'Write here your answer',
                'class': 'form-control'
            })
        }

    def save(self, db_use):
        instance = super(AnswerForm, self).save(db_use)
        instance.display_text = instance.text
        return instance


class AdminReportForm(forms.ModelForm):
    '''
        Form for creating and updating a Report object
        This is implementation is meant to be used in the admin report view
    '''
    template = forms.CharField(widget=forms.HiddenInput, max_length=1024**3, initial=' ')
    order = forms.CharField(widget=forms.HiddenInput, max_length=10, initial='-1')

    class Meta:
        model = Report
        exclude = ('type', 'questions')

report_builder/views/Report.py
import json
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from report_builder.Question.question_loader import process_questions, get_view_type
from django.views.decorators.gzip import gzip_page
from django.contrib.auth.decorators import login_required

from report_builder.forms import AdminReportForm
from report_builder.models import Report


def process_template(request, report, view_type, reportbyproj=None):
    '''
        Loads the questions of the given report, works both for the admin and responsable views

        If ``reportbyproj`` is provided, it also loads the answers of the questions in this report
    '''
    categories = report.template
    i = 0
    for category in categories:
        ii = 0
        for subcategory in category['subcategories']:
            if subcategory['questions']:
                questions = process_questions(request, report.pk, subcategory['questions'], view_type=view_type,
                                              reportbyproj=reportbyproj)
                categories[i]['subcategories'][ii]['questions'] = questions
            ii += 1
        i += 1
    return categories


@gzip_page
@login_required
def admin(request, pk=None):
    '''
        Main administration view for report templates

        Requires the 'template_admin' permission to get access to it. In case the user don't have this permission
        the view renders a page with message explaining the lack of privileges
    '''
    if request.user.has_perm('derb.template_admin'):
        report = None
        if pk:
            report = get_object_or_404(Report, pk=pk)

        if report.opening_date <= datetime.now().date():
            return render(request, 'admin/out_of_date.html')

        admin_views = get_view_type('admin')

        palette = {}

        for name, value in admin_views.items():
            palette[name] = value.minimal_representation

        categories = process_template(request, report, view_type='admin', reportbyproj=None)

        form = AdminReportForm(instance=report)
        context = {
            'report': report,
            'palette': palette,
            'categories': categories,
            'form': form
        }
        return render(request, 'admin/report.html', context=context)
    else:
        return render(request, 'global/permission_denied.html')


@login_required
def save_admin(request, pk):
    '''
        Allows to save the report template in the database
    '''
    if request.method == 'POST':
        if request.user.has_perm('derb.template_admin'):
            report = get_object_or_404(Report, pk=pk)
            old_questions = report.template
            form = AdminReportForm(request.POST, instance=report)

            if form.is_valid():
                rep = form.save(False)
                rep.template = json.loads(form.cleaned_data['template'])
                rep.save()

                # Delete repeated questions
                # Build report object

                return HttpResponse('1')
            else:
                return render(request, 'admin/report_form.html', {'form': form, 'report': report})

        else:
            return render(request, 'global/permission_denied.html')

report_builder/templates/revisor/integer_question.html
{% include 'derb/base.html' %}

{% load static i18n %}
{% block main_block %}
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <div class="alert alert-success">
            <strong>{% trans 'Success:' %}</strong> {{ message }}
          </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="alert alert-danger">
            <strong>{% trans 'Error:' %}</strong> {{ message }}
          </div>
        {% endif %}
      {% endfor %}

      <div class="panel panel-default">
        <div class="panel-heading">
          {% trans 'Integer question (reviewer)' %}
        </div>
        <div class="panel-body">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-offset-1 col-md-10">
              <div class="panel panel-info">
                <div class="panel-heading">
                  <div class="panel-title">
                    {{ question.text|safe }}
                  </div>
                </div>
                <div class="panel-body">
                  <p>
                    <strong>Answer:</strong>
                  </p>
                  {% if answer %}
                    <div class="text-center">
                      {{ answer.display_text|safe }}
                    </div>
                    <p>
                      <strong>Annotation:</strong>
                    </p>
                    <div class="text-center">
                      {{ answer.annotation|safe }}
                    </div>
                    <br>
                    <br>
                  {% else %}
                    <div class="text-center text-muted">
                      Unanswered
                    </div>
                  {% endif %}
                </div>

              </div>
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <strong>Observations</strong>
                </div>
                <div class="panel-body">
                  <div id="observations">
                    {% for observation in answer.observation_set.all %}
                      <div class="well well-sm">
                        <strong>{{ observation.text }}</strong><span
                          >  {{ observation.reviewer.user }}</span>
                      </div>
                    {% empty %}
                      <i>No observations yet</i>
                    {% endfor %}
                  </div>
                  <br>
                  <br>
                  <form action="." method="post">
                    {% csrf_token %}
                    {{ form.text }}
                    <br>
                    <div class="text-right">
                      <input class="btn btn-primary" type="button" onclick="submit_observation();" value="Submit">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block body_js %}
  <script>
    var observation_url = "{% url 'report_builder:submit_new_observation' %}";
    var report_pk = "{{ question.report.pk }}";
    var question_pk = "{{ question.pk }}";
    var answer_pk = "{{ answer.pk }}";
  </script>
  <script src="{% static 'report_builder/js/derb_subcomponents/observations.js' %}"></script>
{% endblock %}

report_builder/templates/revisor/observations.html
<div class="well well-sm">
	<strong>{{ observation.text }}</strong><span
	> {{ observation.reviewer.user }}</span>
</div>

report_builder/templates/revisor/simple_text_question.html
{% include 'derb/base.html' %}

{% load static i18n %}
{% block main_block %}
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <div class="alert alert-success">
            <strong>{% trans 'Success:' %}</strong> {{ message }}
          </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="alert alert-danger">
            <strong>{% trans 'Error:' %}</strong> {{ message }}
          </div>
        {% endif %}
      {% endfor %}

      <div class="panel panel-default">
        <div class="panel-heading">
          {% trans 'Simple text question (reviewer)' %}
        </div>
        <div class="panel-body">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-offset-1 col-md-10">
              <div class="panel panel-info">
                <div class="panel-heading">
                  <div class="panel-title">
                    {{ question.text|safe }}
                  </div>
                </div>
                <div class="panel-body">
                  <p>
                    <strong>Answer:</strong>
                  </p>
                  {% if answer %}
                    <div class="text-center">
                      {{ answer.display_text|safe }}
                    </div>
                    <p>
                      <strong>Annotation:</strong>
                    </p>
                    <div class="text-center">
                      {{ answer.annotation|safe }}
                    </div>
                    <br>
                    <br>
                  {% else %}
                    <div class="text-center text-muted">
                      Unanswered
                    </div>
                  {% endif %}
                </div>

              </div>
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <strong>Observations</strong>
                </div>
                <div class="panel-body">
                  <div id="observations">
                    {% for observation in answer.observation_set.all %}
                      <div class="well well-sm">
                        <strong>{{ observation.text }}</strong><span
                          >  {{ observation.reviewer.user }}</span>
                      </div>
                    {% empty %}
                      <i>No observations yet</i>
                    {% endfor %}
                  </div>
                  <br>
                  <br>
                  <form action="." method="post">
                    {% csrf_token %}
                    {{ form.text }}
                    <br>
                    <div class="text-right">
                      <input class="btn btn-primary" type="button" onclick="submit_observation();" value="Submit">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block body_js %}
  <script>
    var observation_url = "{% url 'report_builder:submit_new_observation' %}";
    var report_pk = "{{ question.report.pk }}";
    var question_pk = "{{ question.pk }}";
    var answer_pk = "{{ answer.pk }}";
  </script>
  <script src="{% static 'report_builder/js/derb_subcomponents/observations.js' %}"></script>
{% endblock %}

report_builder/templates/revisor/unique_selection_question.html
{% include 'derb/base.html' %}

{% load static i18n %}
{% block main_block %}
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <div class="alert alert-success">
            <strong>{% trans 'Success:' %}</strong> {{ message }}
          </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="alert alert-danger">
            <strong>{% trans 'Error:' %}</strong> {{ message }}
          </div>
        {% endif %}
      {% endfor %}

      <div class="panel panel-default">
        <div class="panel-heading">
          {% trans 'Unique Selection question (reviewer)' %}
        </div>
        <div class="panel-body">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-offset-1 col-md-10">
              <div class="panel panel-info">
                <div class="panel-heading">
                  <div class="panel-title">
                    {{ question.text|safe }}
                  </div>
                </div>
                <div class="panel-body">
                  <p>
                    <strong>Answer:</strong>
                  </p>
                  {% if answer %}
                    <div class="text-center">
                      {{ answer.display_text|safe }}
                    </div>
                    <p>
                      <strong>Annotation:</strong>
                    </p>
                    <div class="text-center">
                      {{ answer.annotation|safe }}
                    </div>
                    <br>
                    <br>
                  {% else %}
                    <div class="text-center text-muted">
                      Unanswered
                    </div>
                  {% endif %}
                </div>

              </div>
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <strong>Observations</strong>
                </div>
                <div class="panel-body">
                  <div id="observations">
                    {% for observation in answer.observation_set.all %}
                      <div class="well well-sm">
                        <strong>{{ observation.text }}</strong><span
                          >  {{ observation.reviewer.user }}</span>
                      </div>
                    {% empty %}
                      <i>No observations yet</i>
                    {% endfor %}
                  </div>
                  <br>
                  <br>
                  <form action="." method="post">
                    {% csrf_token %}
                    {{ form.text }}
                    <br>
                    <div class="text-right">
                      <input class="btn btn-primary" type="button" onclick="submit_observation();" value="Submit">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block body_js %}
  <script>
    var observation_url = "{% url 'report_builder:submit_new_observation' %}";
    var report_pk = "{{ question.report.pk }}";
    var question_pk = "{{ question.pk }}";
    var answer_pk = "{{ answer.pk }}";
  </script>
  <script src="{% static 'report_builder/js/derb_subcomponents/observations.js' %}"></script>
{% endblock %}