derb/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',
        include('report_builder.urls', namespace='report_builder')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^password_recovery/', include('password_reset.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

# DEPENDENCIES URLS
urlpatterns += [
    #url(r'^ckeditor/', include('ckeditor.urls'))
]

report_builder/urls.py
from django.conf.urls import include
from django.conf.urls import url

from report_builder import initial_views as init
from report_builder import views
from report_builder.Question import QuestionView
from report_builder.Question.QuestionType import (table_question,
                                                  simple_text_question,
                                                  multiple_selection_question,
                                                  boolean_question,
                                                  integer_question,
                                                  float_question,
                                                  unique_selection_question,
                                                  model_info,
                                                  question_model_info)
from report_builder.Question.QuestionType.simple_text_question import submit_new_observation
from report_builder.Question.QuestionType.unique_selection_question import get_catalog_display_fields
from report_builder.Question.question_loader import process_question
from report_builder.views import Report

# Boolean question
# Integer question
# Float question
# Simple text question
# Unique selection question
# Multiple selection question
# Model info
# Model info with questions
question_types_urls = [
    url(r'base/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', QuestionView.QuestionViewAdmin.as_view(),
        name='base_question_admin'),
    url(r'base/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', QuestionView.QuestionViewResp.as_view(),
        name='base_question_resp'),
    url(r'boolean/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', boolean_question.BooleanQuestionViewAdmin.as_view(),
        name='boolean_question_admin'),
    url(r'boolean/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewResp.as_view(),
        name='boolean_question_resp'),
    url(r'boolean/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewPDF.as_view(),
        name='boolean_question_pdf'),
    url(r'boolean/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        boolean_question.BooleanQuestionViewReviewer.as_view(),
        name='boolean_question_revisor'),
    url(r'boolean/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewCSV.as_view(),
        name='boolean_question_csv'),
    url(r'boolean/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewJSON.as_view(),
        name='boolean_question_json'),
    url(r'boolean/spss/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', boolean_question.BooleanQuestionViewSPSS.as_view(),
        name='boolean_question_spss'),
    url(r'integer/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', integer_question.IntegerQuestionViewAdmin.as_view(),
        name='integer_question_admin'),
    url(r'integer/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', integer_question.IntegerQuestionViewResp.as_view(),
        name='integer_question_resp'),
    url(r'integer/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', integer_question.IntegerQuestionViewPDF.as_view(),
        name='integer_question_pdf'),
    url(r'integer/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        integer_question.IntegerQuestionViewReviewer.as_view(),
        name='integer_question_revisor'),
    url(r'integer/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        integer_question.IntegerQuestionViewCSV.as_view(),
        name='integer_question_csv'),
    url(r'integer/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        integer_question.IntegerQuestionViewJSON.as_view(),
        name='integer_question_json'),
    url(r'float/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', float_question.FloatQuestionViewAdmin.as_view(),
        name='float_question_admin'),
    url(r'float/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', float_question.FloatQuestionViewResp.as_view(),
        name='float_question_resp'),
    url(r'float/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', float_question.FloatQuestionViewPDF.as_view(),
        name='float_question_pdf'),
    url(r'simple/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$',
        simple_text_question.SimpleTextQuestionViewAdmin.as_view(),
        name='simple_text_question_admin'),
    url(r'simple/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewResp.as_view(),
        name='simple_text_question_resp'),
    url(r'simple/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)', simple_text_question.SimpleTextQuestionViewPDF.as_view(),
        name='simple_text_question_pdf'),
    url(r'simple/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        simple_text_question.SimpleTextQuestionViewReviewer.as_view(),
        name='simple_text_question_revisor'),
    url(r'simple/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewCSV.as_view(),
        name='simple_text_question_csv'),
    url(r'simple/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$', simple_text_question.SimpleQuestionViewJSON.as_view(),
        name='simple_text_question_json'),
    url(r"unique/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        unique_selection_question.UniqueSelectionQuestionViewAdmin.as_view(),
        name="unique_selection_admin"),
    url(r"unique/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        unique_selection_question.UniqueSelectionQuestionViewResp.as_view(),
        name="unique_selection_resp"),
    url(r"unique/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)",
        unique_selection_question.UniqueSelectionQuestionViewPDF.as_view(),
        name="unique_selection_pdf"),
    url(r'unique/revisor/(?P<report_pk>\d+)/(?P<question_pk>\d+)',
        unique_selection_question.UniqueSelectionQuestionViewReviewer.as_view(),
        name='unique_selection_question_revisor'),
    url(r'unique/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        unique_selection_question.UniqueQuestionViewCSV.as_view(),
        name='unique_selection_csv'),
    url(r'unique/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        unique_selection_question.UniqueQuestionViewJSON.as_view(),
        name='unique_selection_json'),
    url(r"table/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        table_question.TableQuestionViewAdmin.as_view(),
        name="table_question_admin"),
    url(r"table/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        table_question.TableQuestionViewResp.as_view(),
        name="table_question_resp"),
    url(r"table/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)",
        table_question.TableQuestionViewPDF.as_view(),
        name="table_question_pdf"),
    url(r'table/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        table_question.TableQuestionViewCSV.as_view(),
        name='table_question_csv'),
    url(r'table/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        table_question.TableQuestionViewJSON.as_view(),
        name='table_question_json'),
    url(r"multiple/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$",
        multiple_selection_question.MultipleSelectionQuestionViewAdmin.as_view(),
        name="multiple_selection_admin"),
    url(r"multiple/resp/(?P<report_pk>\d+)/(?P<question_pk>\d+)$",
        multiple_selection_question.MultipleSelectionQuestionViewResp.as_view(),
        name="multiple_selection_resp"),
    url(r'multiple/pdf/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewPDF.as_view(),
        name='multiple_seletion_question_pdf'),
    url(r'multiple/csv/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewCSV.as_view(),
        name='multiple_selection_question_csv'),
    url(r'multiple/json/(?P<report_pk>\d+)/(?P<question_pk>\d+)$',
        multiple_selection_question.MultipleSelectionQuestionViewJSON.as_view(),
        name='multiple_selection_question_json'),
    url(r'model_info/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?', model_info.ModelInfoViewAdmin.as_view(),
        name='model_info_question'),
    url(r'question_model_info/admin/(?P<report_pk>\d+)/(?P<question_pk>\d+)?',
        question_model_info.QuestionModelInfoViewAdmin.as_view(), name='question_model_info_question')
]

# Report views
report_views_urls = [
    url(r'^new/$', init.NewReportView.as_view(), name='new_report'),
    url(r'^new/(?P<pk>\d+)$', init.NewReportTemplate,
        name='new_report_from_template'),
    url(r'^admin/template/(?P<pk>\d+)$', Report.admin, name='admin_report'),
    url(r'^admin/template/(?P<pk>\d+)/save$',
        Report.save_admin, name='admin_save_report'),
]

# Question processing
question_process_urls = [
    url(r'(?P<type>admin)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)?$', process_question,
        name='process_admin'),
    url(r'(?P<type>responsable)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)/(?P<answer_pk>\d+)?$',
        process_question, name='process_responsable'),
    url(r'(?P<type>revisor)/(?P<view_type>\w+)/(?P<report_pk>\d+)/(?P<question_pk>\d+)/(?P<answer_pk>\d+)?$',
        process_question, name='process_revisor')
]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^js/ckeditor_config.js', views.get_js_editor,
        name='js_ckeditor_config'),
    url(r'^init$', init.InitialIndexView.as_view(), name='init'),
    url(r'^question_types/', include(question_types_urls)),
    url(r'^report/', include(report_views_urls)),
    url(r'^question_processing/', include(question_process_urls)),
    url(r"^get_catalog_display_fields", get_catalog_display_fields,
        name='get_catalog_display_fields'),
    url(r"^submit_new_observation$", submit_new_observation,
        name='submit_new_observation')
]

report_builder/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from report_builder.models import Question, Answer, Report
from report_builder.report_shortcuts import get_question_permission


class QuestionForm(forms.ModelForm):
    children = forms.CharField

    class Meta:
        model = Question
        fields = ('text', 'help', 'required', 'id')
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 6,
                'placeholder': 'Write your question here',
                'class': 'form-control'
            }),
            'help': forms.Textarea(attrs={
                'cols': 80,
                'rows': 5,
                'placeholder': 'A little help never hurts',
                'class': 'form-control'
            })
        }
        exclude = ('order',)


class AnswerForm(forms.ModelForm):
    """
        TODO: docstring
    """

    def clean_text(self):
        text = self.cleaned_data['text']
        required = get_question_permission(self.instance.question)
        if required == 1 and not text:
            raise ValidationError(_('This field is required'), code='required')
        return text

    class Meta:
        model = Answer
        fields = ('annotation', 'text')
        widgets = {
            'annotation': forms.Textarea(attrs={
                'rows': 9,
                'placeholder': 'Annotations',
                'class': 'form-control'
            }),
            'text': forms.Textarea(attrs={
                'rows': 6,
                'placeholder': 'Write here your answer',
                'class': 'form-control'
            })
        }

    def save(self, db_use):
        instance = super(AnswerForm, self).save(db_use)
        instance.display_text = instance.text
        return instance


class AdminReportForm(forms.ModelForm):
    '''
        Form for creating and updating a Report object
        This is implementation is meant to be used in the admin report view
    '''
    template = forms.CharField(widget=forms.HiddenInput, max_length=1024**3, initial=' ')
    order = forms.CharField(widget=forms.HiddenInput, max_length=10, initial='-1')

    class Meta:
        model = Report
        exclude = ('type', 'questions')

report_builder/views/Report.py
import json
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from report_builder.Question.question_loader import process_questions, get_view_type
from django.views.decorators.gzip import gzip_page
from django.contrib.auth.decorators import login_required

from report_builder.forms import AdminReportForm
from report_builder.models import Report


def process_template(request, report, view_type, reportbyproj=None):
    '''
        Loads the questions of the given report, works both for the admin and responsable views

        If ``reportbyproj`` is provided, it also loads the answers of the questions in this report
    '''
    categories = report.template
    i = 0
    for category in categories:
        ii = 0
        for subcategory in category['subcategories']:
            if subcategory['questions']:
                questions = process_questions(request, report.pk, subcategory['questions'], view_type=view_type,
                                              reportbyproj=reportbyproj)
                categories[i]['subcategories'][ii]['questions'] = questions
            ii += 1
        i += 1
    return categories


@gzip_page
@login_required
def admin(request, pk=None):
    '''
        Main administration view for report templates

        Requires the 'template_admin' permission to get access to it. In case the user don't have this permission
        the view renders a page with message explaining the lack of privileges
    '''
    if request.user.has_perm('derb.template_admin'):
        report = None
        if pk:
            report = get_object_or_404(Report, pk=pk)

        if report.opening_date <= datetime.now().date():
            return render(request, 'admin/out_of_date.html')

        admin_views = get_view_type('admin')

        palette = {}

        for name, value in admin_views.items():
            palette[name] = value.minimal_representation

        categories = process_template(request, report, view_type='admin', reportbyproj=None)

        form = AdminReportForm(instance=report)
        context = {
            'report': report,
            'palette': palette,
            'categories': categories,
            'form': form
        }
        return render(request, 'admin/report.html', context=context)
    else:
        return render(request, 'global/permission_denied.html')


@login_required
def save_admin(request, pk):
    '''
        Allows to save the report template in the database
    '''
    if request.method == 'POST':
        if request.user.has_perm('derb.template_admin'):
            report = get_object_or_404(Report, pk=pk)
            old_questions = report.template
            form = AdminReportForm(request.POST, instance=report)

            if form.is_valid():
                rep = form.save(False)
                rep.template = json.loads(form.cleaned_data['template'])
                rep.save()

                # Delete repeated questions
                # Build report object

                return HttpResponse('1')
            else:
                return render(request, 'admin/report_form.html', {'form': form, 'report': report})

        else:
            return render(request, 'global/permission_denied.html')

report_builder/templates/initials/index.html
{% extends 'derb/base.html' %}
{% load static %}

{# TITLE #}
{% block title %}Derb | Django Enterprise Report Builder{% endblock %}

{# TODO: FAVICON #}
{% block favicon %}
  <link rel="icon" href="{% static 'admin/img/icon-alert.svg' %}" type="image/svg"/>
  <link rel="shorcut icon" href="{% static 'admin/img/icon-alert.svg' %}"/>
{% endblock %}

{% block header_js %}
  <link type="text/css" href="{% static 'report_builder/css/jquery.dataTables.min.css' %}">
  <link type="text/css" href="{% static 'report_builder/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block body_js %}
  <script src="{% static 'report_builder/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'report_builder/js/dataTables.bootstrap.js' %}" type="text/javascript"></script>
{% endblock %}

{% block main_block %}
  <div class="row">
    <div class="panel-group col-md-10 col-md-offset-1" id="accordion">
      {% for view in views %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#a_{{ forloop.counter }}">
                {{ view.title }}
              </a>
            </h3>
          </div>
          <div id="a_{{ forloop.counter }}"
               class="panel-collapse collapse {% if forloop.counter == 1 %}in{% endif %}">
            <div class="panel-body">
              {{ view.content | safe }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="well col-md-10 col-md-offset-1 text-center">
          <h1>
            <small>Sorry, currently you don't have any funcionality in the system.</small>
          </h1>
          <br/>
          <p class="text-danger">If you have any question, ask the administrator.</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

report_builder/templates/initials/initial_responsable.html
{% load project_tags %}

<div class="well text-center" id="div_table_responsable_reports">
    <div class="form-inline">
        <table id="table_responsable_reports" class="table" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th class="text-center">Project code</th>
                <th class="text-center">Project name</th>
                <th class="text-center">Organization</th>
                <th class="text-center">Project validity</th>
                <th class="text-center">Status</th>
                <th class="text-center">Revision</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for element in object_list %}
                {{ element.report | get_project }}
                <tr>
                    <td>{{ element.report.projects.project_code }}</td>
                    <td>{{ element.report.projects.project_name }}</td>
                    <td>{{ element.report.projects.organization }}</td>
                    <td>{{ element.report.opening_date }} - {{ element.report.submit_date }}</td>
                    <td>{{ element.report.get_state_display }}</td>
                    <td>
                        {% include 'initials/components/reviewer_action_modal.html' %}
                        <a href="#accordion">
                            <div class="progress progress-striped" data-toggle="modal"
                                 data-target="#mod_{{ element.report.pk }}" title="Click for details">
                                <div class="progress-bar" role="progressbar"
                                     aria-valuenow="{{ element.report.review_percentage }}" aria-valuemin="0"
                                     aria-valuemax="100" style="width: {{ element.report.review_percentage }}%;">
                                    <span class="text-danger">{{ element.report.review_percentage }}%</span>
                                </div>
                            </div>
                        </a>
                    </td>
                    {% if element.report.state != 1 and element.report.state != 4 %}
                        {% if element.type == 'responsable' %}
                            <td><a href="{% url 'report_builder:report_responsable' %}">Go to report</a></td>
                        {% else %}
                            <td><a href="{% url 'report_builder:report_reviewer' %}">Go to report</a></td>
                        {% endif %}
                    {% else %}
                        <td>---</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br><br><br>
    {% if not all_reports %}
        <a class="btn btn-default btn-all-current" data-loading-text="Loading all reports...">Show all reports</a>
    {% else %}
        <a class="btn btn-default" data-loading-text="Loading current reports..." onclick="show_reports('{% url "report_builder:initial_responsable" %}');">Show only current reports</a>
    {% endif %}
</div>

{% include 'initials/components/table_responsable_reports_js_handler.html' %}

report_builder/templates/initials/initial_reviewer.html
{% load project_tags %}

<div class="well text-center">
  <div id="div_table_reviewer_reports" class="form-inline">
    <table id="table_reviewer_reports" class="table" cellspacing="0" width="100%">
      <thead>
      <tr>
        <td class="text-center">Project code</td>
        <td class="text-center">Project name</td>
        <td class="text-center">Organization</td>
        <td class="text-center">Project validity</td>
        <td class="text-center">Review</td>
        <td class="text-center">Actions</td>
      </tr>
      </thead>
      <tbody>
      {% for report in object_list %}
        {{ report | get_project }}
        <tr>
          <td>{{ report.projects.project_code }}</td>
          <td>{{ report.projects.project_name }}</td>
          <td>{{ report.projects.organization }}</td>
          <td>{{ report.start_date }} - {{ report.submit_date }}</td>
          <td>
            {% include 'initials/components/reviewer_action_modal.html' %}
            <a href="#accordion">
              <div class="progress progress-striped" data-toggle="modal"
                   data-target="#mod_{{ report.pk }}" title="Click for details">
                <div class="progress-bar" role="progressbar"
                     aria-valuenow="{{ report.review_porcentage }}" aria-valuemin="0"
                     aria-valuemax="100" style="width: {{ report.review_porcentage }}%;">
                  <span class="text-danger">{{ report.review_porcentage }}%</span>
                </div>
              </div>
            </a>
          </td>
          <td><a href=""></a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% include 'initials/components/table_reviewer_reports_js_handler.html' %}

report_builder/templates/initials/initial_template_admin.html
<div id="message" class="hide">
    <div class="alert alert-danger alert-dismissable fade in">
        <button type="button" class="close" onclick="$('#message').addClass('hide')">&times;</button>
        <strong>Atention:</strong> you cannot edit a report template that's already open
    </div>
</div>

<div class="modal fade" id="new_with_template" tabindex="-1" role="dialog" aria-labelledby="new_template_modal"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="new_template_modal">Select a report template</h4>
            </div>
            <div class="modal-body form-inline">
                <div class="alert alert-info">Please select the template you want to use to create a new one</div>
                Report:
                <select class="form-control" id="modal_select_new"
                        onchange="new_report_template('{% url "report_builder:new_report_from_template" 0 %}');">
                    {% for report in object_list %}
                        <option value="{{ report.0.pk }}">{{ report.0.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Close</button>
                <a type="button" href="{% if object_list %}{% url 'report_builder:new_report_from_template' object_list.0.0.pk %}{% else %}#{% endif %}"
                   class="btn btn-primary" id="new_report_template">Accept</a>
            </div>
        </div>
    </div>
</div>

<div class="well text-center">
    <div id="div_table_admin_reports">
        <table id="table_admin_reports" class="table" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Type</th>
                <th class="text-center">Opening date</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for report in object_list %}
                <tr>
                    <td>{{ report.0.name }}</td>
                    <td>{{ report.0.type }}</td>
                    <td>{{ report.0.opening_date }}</td>
                    <td>
                        {% if report.1 %}
                            <a href="{% url 'report_builder:admin_report' report.0.pk %}">Edit</a>
                        {% else %}
                            <a href="#accordion" onclick="$('#message').removeClass('hide');">Edit</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br><br><br>
    <button class="btn btn-default text-center" onclick="$('#new_with_template').modal();">
        Create new report from existing template
    </button>
    <a class="btn btn-default text-center" href="{% url 'report_builder:new_report' %}">
        Create new empty report
    </a>
</div>

{% include 'initials/components/table_admin_report_js_handler.html' %}

report_builder/templates/initials/new_report.html
{% extends 'derb/base.html' %}
{% load static %}

{% block title %}New report template{% endblock %}

{# TODO: FAVICON #}
{% block favicon %}
    <link rel="icon" href="{% static 'admin/img/icon-alert.svg' %}" type="image/svg"/>
    <link rel="shorcut icon" href="{% static 'admin/img/icon-alert.svg' %}"/>
{% endblock %}

{% block main_block %}
    <div class="col-md-5 col-md-offset-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title text-center">New report template</h3>
            </div>
            <div class="panel-body">
                <div class="alert alert-info text-center">
                    Please fill the required information. You will be automatically redirected to the report's question
                    definition page
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    <table class="table-condensed">
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-info pull-right" type="submit" value="Create" />
                </form>
            </div>
        </div>
    </div>

    <script>
        $('input[type=text], select').addClass('form-control');
    </script>
{% endblock %}

{% block body_js %}
    <script src="{% static 'report_builder/js/derb_subcomponents/new_report.js' %}"></script>
{% endblock %}